# Generated by Django 4.0.3 on 2022-03-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('title', 'price')},
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.URLField(verbose_name='Link to Image'),
        ),
    ]
