# Generated by Django 4.0.3 on 2022-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google'), ('Twitter', 'Twitter')], default='', max_length=7),
            preserve_default=False,
        ),
    ]
