# Generated by Django 4.0.3 on 2022-03-16 11:15

from django.db import migrations, models
import petstagram.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pet_name_alter_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[petstagram.main_app.validators.validate_file_max_size_in_mb])),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='main_app.pet')),
            ],
        ),
    ]
