# Generated by Django 4.0.3 on 2022-03-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
