# Generated by Django 4.0.3 on 2022-03-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
